### ISSUE TITLE
[13.0] BUG: helpdesk_mgmt

### ISSUE THREAD

**Issue by amon-ra** [OCA/helpdesk#210]
I have the following error:
```
2021-03-25 10:39:11,752 55 ERROR erp.oondeo.es odoo.sql_db: bad query: SELECT "res_partner".id FROM "res_partner" WHERE (("res_partner"."id" in (%s,%s))  AND  ("res_partner"."active" = %s)) ORDER BY "res_partner"."display_name"
ERROR: can't adapt type 'res.partner'
2021-03-25 10:39:11,752 55 INFO erp.oondeo.es odoo.addons.fetchmail_set_unread.models.fetchmail_server: Failed to process mail from imap server info.
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/fetchmail_set_unread/models/fetchmail_server.py", line 51, in fetch_mail
    res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
  File "/opt/odoo/auto/addons/fetchmail_thread_default/models/mail_thread.py", line 29, in message_process
    model, message, custom_values, save_original, strip_attachments, thread_id
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 1144, in message_process
    thread_id = self._message_route_process(message, msg_dict, routes)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 1058, in _message_route_process
    thread = ModelCtx.message_new(message_dict, custom_values)
  File "/opt/odoo/auto/addons/helpdesk_mail_ticket_filter/models/helpdesk_ticket.py", line 16, in message_new
    ticket = super().message_new(msg, custom_values)
  File "/opt/odoo/auto/addons/helpdesk_mgmt/models/helpdesk_ticket.py", line 217, in message_new
    ticket.message_subscribe(partner_ids)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 2758, in message_subscribe
    partner_ids = self.env['res.partner'].sudo().search([('id', 'in', partner_ids), ('active', '=', True)]).ids
  File "/opt/odoo/auto/addons/l10n_es_partner/models/res_partner.py", line 35, in search
    args, offset=offset, limit=limit, order=order, count=count
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 706, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4497, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: can't adapt type 'res.partner'
```

I have changed the line: https://github.com/OCA/helpdesk/blob/7c1715df5b4efcdd992fa7ea557a3130123b498a/helpdesk_mgmt/models/helpdesk_ticket.py#L211 to p.id and is working.
Is this correct?

**Comment by amon-ra** [comment]
Sorry duplicated.
