### ISSUE TITLE
Error Install Helpdesk Management 

### ISSUE THREAD

**Issue by vnptphuyen** [OCA/helpdesk#250]
Dear, Team Dev
I'm install module Helpdesk Management  then error below. Please help me.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/models.py", line 4205, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/models.py", line 4134, in _load_records_create
    return self.create(values)
  File "<decorator-gen-134>", line 2, in create
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/mail/models/mail_alias.py", line 115, in create
    vals['alias_name'] = self._clean_and_check_unique(vals.get('alias_name'))
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/mail/models/mail_alias.py", line 154, in _clean_and_check_unique
    raise UserError(_('The e-mail alias is already used. Please enter another one.'))
odoo.exceptions.UserError: Alias e-mail đã được sử dụng. Vui lòng nhập một cái khác.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/bitnami/odoo/venv/lib/python3.8/site-packages/odoo/addons/helpdesk_mgmt/data/helpdesk_data.xml:227, near
<record id="mail_alias_lead_info_helpdesk" model="mail.alias">
            <field name="alias_name">helpdesk</field>
            <field name="alias_model_id" ref="model_helpdesk_ticket"/>
            <field name="alias_user_id" ref="base.user_admin"/>
            <field name="alias_parent_model_id" ref="model_helpdesk_ticket_team"/>
        </record>
![image](https://user-images.githubusercontent.com/63487694/128614118-3b17ae2a-4e4c-4905-beaf-bc9d79a73281.png)

**Comment by dalonsod** [comment]
Hello @vnptphuyen . As error message shows, `helpdesk_mgmt` addon tries to create a mail alias whose name is "helpdesk" (https://github.com/OCA/helpdesk/blob/14.0/helpdesk_mgmt/data/helpdesk_data.xml#L227), and addon installation should fail if that alias name already exists.

Please check if that alias name is already in use in your system, or make an installation from scratch and check if error persists.

**Comment by vnptphuyen** [comment]
thanks you.
