### ISSUE TITLE
Ticket Email Templates are not working

### ISSUE THREAD

**Issue by valasule** [OCA/helpdesk#361]
<!-- Provide a general summary of the issue in the Title above.
Just recently I am getting a python error when handling tickets that trigger the use of an email template, i.e. creating, moving, assigning, closing.  If I remove the email template from the stage all actions work correctly.

## Module
helpdesk_mgmt

## Describe the bug
This was first noticed when attempting to move a ticket to my Done stage which also closes the ticket and sends an email using a template.  I then tested it with other actions and had the same result.  The full error message is:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1390, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1382, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 397, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 377, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-176>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/git/helpdesk/helpdesk_mgmt/models/helpdesk_ticket.py", line 128, in create
    return super().create(vals)
  File "<decorator-gen-135>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 310, in create
    thread._message_track_post_template(changes)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 580, in _message_track_post_template
    templates = self._track_template(changes)
  File "/opt/odoo/git/helpdesk/helpdesk_mgmt/models/helpdesk_ticket.py", line 179, in _track_template
    "subtype_id": self.env["ir.model.data"]._xmlid_to_res_id(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.model.data' object has no attribute '_xmlid_to_res_id'

## To Reproduce
**Affected versions**: 14

1. Configure a ticketing stage and make sure that it has an email template assigned
2. Open a new ticket and fill out all of the information
3. Assign it to the stage configured in Step 1
4. Save the ticket

**Expected behavior**
It is expected that the ticket will be created/moved and the email set in the Email Template for the stage will be sent to the defined recipients.  Attached is one of the email templates I have defined that is displaying this behavior.
[mail.template.csv](https://github.com/OCA/helpdesk/files/9471533/mail.template.csv)

**Additional context**
I have not tested this on my sandbox server but will as soon as I am able

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem in runboat? Odoo version?

**Comment by valasule** [comment]
Hello @pedrobaeza 
Well that is pretty odd, I filled everything out and it didn't save it to the issue.  I will get it all written back out and submit in a sec.

**Comment by valasule** [comment]
## Module
helpdesk_mgmt

## Describe the bug
Recently the ticket email templates are throwing an error when they are activated.

## To Reproduce
**Affected versions**: 14

Steps to reproduce the behavior:
1. Configure a Stage and make sure the Email Template is set
2. Create a ticket in that stage
3. Save the ticket (The same behavior happens when a ticket is moved to a stage that uses an Email Template)

**Expected behavior**
It is expected that the Ticket should trigger the email template and an email is sent to the defined recipients.

**Additional context**
This just started happening in the last week

**Comment by valasule** [comment]
[mail.template.csv](https://github.com/OCA/helpdesk/files/9471658/mail.template.csv)
This is a dump of one of the templates I use that is having the issue

**Comment by pedrobaeza** [comment]
Error message?

Maybe a translation problem?

**Comment by valasule** [comment]
This is the full error I get when it tries to execute the template:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1390, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1382, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 397, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 377, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-176>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/git/helpdesk/helpdesk_mgmt/models/helpdesk_ticket.py", line 128, in create
    return super().create(vals)
  File "<decorator-gen-135>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 310, in create
    thread._message_track_post_template(changes)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 580, in _message_track_post_template
    templates = self._track_template(changes)
  File "/opt/odoo/git/helpdesk/helpdesk_mgmt/models/helpdesk_ticket.py", line 179, in _track_template
    "subtype_id": self.env["ir.model.data"]._xmlid_to_res_id(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.model.data' object has no attribute '_xmlid_to_res_id'

**Comment by valasule** [comment]
> Error message?
> 
> Maybe a translation problem?

I was splitting it all out in case the error is what caused my initial post to not post any content

**Comment by valasule** [comment]
I think something weird happened with a code pull.  I tested on my sandbox and it worked right so I recloned fresh from git, upgraded the helpdesk_mgmt app through the UI and it worked without an error.  Closing it off, apologies for the alarm.
