### ISSUE TITLE
[16] we can't update helpdesk_mgmt

### ISSUE THREAD

**Issue by gcobachoesment** [OCA/helpdesk#666]
## Module
helpdesk_mgmt

## Describe the bug
When I try to update helpdesk_mgmt to the latest version the system shows the following error:

2024-12-09 15:57:13,830 8761 CRITICAL 241118_TEST_ESMENT odoo.service.server: Failed to initialize database `241118_TEST_ESMENT`. 
Traceback (most recent call last):
  File "/media/odoo16/source/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/media/odoo16/source/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/media/odoo16/source/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/media/odoo16/source/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/media/odoo16/source/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/media/odoo16/source/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/media/odoo16/source/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/media/odoo16/source/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/media/odoo16/source/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/media/odoo16/source/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/media/odoo16/source/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /media/odoo16/oca_addons/helpdesk/helpdesk_mgmt/views/res_partner_views.xml:3
La vista heredada no puede tener 'grupos' definidos en el registro. Use los atributos de 'grupos' dentro de la definición de la vista

## To Reproduce
We are trying to update from 16.2.2.2 to the latest version 16

Just click update

**Comment by pedrobaeza** [comment]
It seems you have an incorrect inherit group, but I'm afraid it's not something of the module itself. Please check all the views and remove the groups in them. Closing this as no issue with the module.

**Comment by gcobachoesment** [comment]
Oops! that makes sense, sorry and thanks a lot Pedro.
