### ISSUE TITLE
Kanban template Error when clicked on team card

### ISSUE THREAD

**Issue by ivs-cetmix** [OCA/helpdesk#93]
Version affected: 12CE
Modules installed: base + oca helpdesk
Latest commit: https://github.com/OCA/helpdesk/commit/368b9deb6478e3d8bdf3b6f1e0300d0ca8766a9e

Steps to reproduce
1. Install modules from github.
2. Create new clean Odoo db (pg 9.6) with demo data.
3. Install Helpdesk module.
4. Go to Helpdesk menu and click on Team kanban dashboard.
Following error appears:
Error:
Uncaught Error: QWeb2 - template['kanban-box']: Error evaluating template: SyntaxError: Unexpected identifier

http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3374
Traceback:
Error: QWeb2 - template['kanban-box']: Error evaluating template: SyntaxError: Unexpected identifier
    at Object.exception (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3374:7)
    at Engine._render (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3417:12)
    at Engine.render (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3415:151)
    at Class._render (http://localhost:8069/web/content/384-e2ccca3/web.assets_backend.js:1814:451)
    at Class.start (http://localhost:8069/web/content/384-e2ccca3/web.assets_backend.js:1804:1256)
    at Class.prototype.<computed> [as start] (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3538:488)
    at http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:3684:52
    at http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/383-9c2787f/web.assets_common.js:797:467)

**Comment by pedrobaeza** [comment]
Please check #92

**Comment by ivs-cetmix** [comment]
> Please check #92

Thank you! Then it is solved.
